name: test workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -Wall Source.cpp Character.cpp Json_parser.cpp
      - run: ./runTest.sh
      - name: Install googletest and cmake
        run: sudo apt install libgtest-dev
        run: sudo apt install cmake
        run: cd /usr/src/gtest
        run: sudo cmake .
        run: sudo make
        run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest.a
        run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - uses: actions/checkout@v2
      -name: Make makefiles and run Unit tests
        run: cd Unittest
        run: cmake .
        run: make
        run: chmod -x Unittest/runTests
        run: ./Unittest/runTests

