name: test workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ Source.cpp Character.cpp
      - run: ./runTest.sh
      - name: cppcheck
        uses: deep5050/cppcheck-action@master
